# Generated by Django 3.2.2 on 2021-05-13 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=250, verbose_name='Урок')),
                ('Video', models.CharField(max_length=250, verbose_name='Видео')),
                ('abstract', models.TextField(verbose_name='Конспект')),
                ('home_work', models.TextField(verbose_name='Домашнее задание')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ImageField(upload_to='', verbose_name='Ответ')),
                ('comments', models.TextField(verbose_name='Комментарий преподавателя')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Задание выполнено верно')),
                ('from_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brows.lessons', verbose_name='Урок')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
