# Generated by Django 3.2.2 on 2021-05-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brows', '0002_alter_answers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Ответ')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='brows.answers')),
            ],
        ),
    ]
