# Generated by Django 3.2.2 on 2021-05-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brows', '0005_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='from_lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brows.lessons', verbose_name='Урок'),
        ),
    ]
