# Generated by Django 3.2.2 on 2021-05-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brows', '0007_alter_answers_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='from_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brows.lessons', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Ответ'),
        ),
    ]
