# Generated by Django 3.2.2 on 2021-05-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brows', '0008_auto_20210515_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['pk'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
